trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  LIGHTHOUSE_URL: "http://104.211.61.92:4008"
  TARGET_URL: "https://github.com"

steps:

# Install jq
- script: |
    sudo apt-get update
    sudo apt-get install -y jq
  displayName: "Install jq"

- script: |
    echo "Triggering Lighthouse audit..."

    RESPONSE=$(curl --fail --silent --show-error \
      -X POST $(LIGHTHOUSE_URL)/v1/audits \
      -H "Content-Type: application/json" \
      -H "Accept: application/json" \
      -d "{\"url\":\"$(TARGET_URL)\"}")

    echo "$RESPONSE"

    AUDIT_ID=$(echo "$RESPONSE" | jq -r '.id')

    echo "Audit ID: $AUDIT_ID"

    STATUS="RUNNING"

    while [ "$STATUS" = "RUNNING" ]; do
      sleep 10

      RESULT=$(curl --fail --silent --show-error \
        -H "Accept: application/json" \
        $(LIGHTHOUSE_URL)/v1/audits/$AUDIT_ID)

      echo "$RESULT" | jq empty || { echo "Invalid JSON from API"; exit 1; }

      STATUS=$(echo "$RESULT" | jq -r '.status')

      echo "Current status: $STATUS"
    done

    echo "$RESULT" > full-report.json

    echo "Final Report saved."
  displayName: "Trigger + Wait for Lighthouse Audit"

#validatig json
- script: |
    echo "Validating JSON..."

    jq . full-report.json || { echo "Invalid JSON received"; exit 1; }
  displayName: "Validate JSON"

# Generate Summary
- script: |
    echo "Generating summary..."

    jq '{
      id: .id,
      url: .url,
      status: .status,
      timeCreated: .timeCreated,
      timeCompleted: .timeCompleted,
      categories: (
        .report.categories
        | with_entries({ key: .key, value: { score: .value.score } })
      )
    }' full-report.json > summary.json

    echo "Summary:"
    cat summary.json
  displayName: "Generate Summary"

# Publish Artifact
- publish: summary.json
  artifact: LighthouseReport