apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lighthouse
resources:
  - namespace.yaml
  - secret.yaml
  - postgres.yaml
  - lighthouse.yaml
  - backstage.yaml
  - ingress.yaml
